import type { ContextType } from 'react';
import { FinanceContext } from '../context/FinanceContext';
type Finance = NonNullable<ContextType<typeof FinanceContext>>;
const success = async () => true;
export function financeFixture(overrides: Partial<Finance> = {}): Finance {
    return {
        user: { id: 'fixture', name: 'Marina Costa', email: 'fixture@example.invalid', avatar: '' },
        selectedDate: new Date(2026, 8, 1),
        setSelectedDate: () => {},
        transactions: [],
        filteredTransactions: [],
        annualTotals: [],
        categories: [],
        members: [],
        budgetRule: null,
        tags: [],
        tagsEnabled: false,
        configureTags: success,
        saveTag: success,
        removeTag: success,
        notificationsError: null,
        notifications: { items: [], unread: 0, nextCursor: null },
        loadNotifications: async () => ({ items: [], unread: 0, nextCursor: null }),
        readNotifications: success,
        getPushKey: async () => ({ publicKey: null }),
        subscribePush: success,
        unsubscribePush: success,
        getSummary: () => ({
            totalIncome: 0,
            totalSpent: 0,
            currentBalance: 0,
            netBalance: 0,
            memberBalances: {},
            hasSharedTransactions: false,
        }),
        requestError: null,
        isProcessing: false,
        addTransaction: success,
        updateTransaction: success,
        stopRecurrence: success,
        removeTransaction: success,
        addCategory: success,
        updateCategory: success,
        removeCategory: success,
        addMember: success,
        updateMember: success,
        removeMember: success,
        fetchBudgetRule: success,
        updateBudgetRule: success,
        sharing: { connections: [], shares: [], attentionCount: 0 },
        sharingError: null,
        hasMoreSharing: false,
        isLoadingMoreSharing: false,
        loadMoreSharing: () => {},
        inviteMember: success,
        decideConnection: success,
        shareExpense: success,
        decideShare: success,
        proposeShareChange: success,
        decideProposal: success,
        getShareHistory: async () => ({ items: [], nextCursor: null }),
        refreshSharing: () => {},
        logout: () => {},
        ...overrides,
    };
}
