events {}

http {
  resolver 127.0.0.11 valid=30s ipv6=off;

  server {
    listen 80;

    location /api/users {
      set $identity_service identity-service;
      rewrite ^/api/users(.*)$ /users$1 break;
      proxy_pass http://$identity_service:3001;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/transactions {
      set $finance_service finance-service;
      rewrite ^/api/transactions(.*)$ /transactions$1 break;
      proxy_pass http://$finance_service:3002;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/categories {
      set $finance_service finance-service;
      rewrite ^/api/categories(.*)$ /categories$1 break;
      proxy_pass http://$finance_service:3002;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/members {
      set $finance_service finance-service;
      rewrite ^/api/members(.*)$ /members$1 break;
      proxy_pass http://$finance_service:3002;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/budget-rules {
      set $finance_service finance-service;
      rewrite ^/api/budget-rules(.*)$ /budget-rules$1 break;
      proxy_pass http://$finance_service:3002;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/auth/ {
      set $identity_service identity-service;
      rewrite ^/api/auth/(.*)$ /auth/$1 break;
      proxy_pass http://$identity_service:3001;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Host $host;
    }

    location / {
      set $frontend_service frontend;
      proxy_pass http://$frontend_service:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_max_temp_file_size 0;
    }

    # CORS Configuration
    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
    add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;

    add_header 'Access-Control-Max-Age' 1728000 always;

    if ($request_method = 'OPTIONS') {
        return 204;
    }
  }
}
